<h1 align="center">Universal Unary and Binary functions</h1>

In [1]:
import numpy as np

In [2]:
arr1=np.arange(16).reshape(4,4)
arr1[0,0]=1
arr2=np.random.randn(4,4)

<b> Universal Unary Functions </b>

In [16]:
np.sqrt(arr2) #nan = not a number

F:\Conda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[1.19605758, 0.78306858,        nan,        nan],
       [0.33188639,        nan, 0.7754239 , 0.96010167],
       [       nan,        nan,        nan, 1.21102802],
       [       nan, 1.19413348,        nan,        nan]])

In [4]:
np.exp(arr1)

array([[2.71828183e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06]])

In [5]:
np.abs(arr2)

array([[1.43055374, 0.6131964 , 0.52982214, 1.04819381],
       [0.11014858, 0.88182859, 0.60128222, 0.92179522],
       [0.45088797, 1.18817407, 0.54545086, 1.46658887],
       [0.53364913, 1.42595477, 0.76132483, 0.79556188]])

In [6]:
np.fabs(arr2)

array([[1.43055374, 0.6131964 , 0.52982214, 1.04819381],
       [0.11014858, 0.88182859, 0.60128222, 0.92179522],
       [0.45088797, 1.18817407, 0.54545086, 1.46658887],
       [0.53364913, 1.42595477, 0.76132483, 0.79556188]])

In [8]:
np.log1p(arr1)

array([[0.69314718, 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665],
       [2.56494936, 2.63905733, 2.7080502 , 2.77258872]])

In [9]:
np.log2(arr1)

array([[0.        , 0.        , 1.        , 1.5849625 ],
       [2.        , 2.32192809, 2.5849625 , 2.80735492],
       [3.        , 3.169925  , 3.32192809, 3.45943162],
       [3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [10]:
np.log(arr1)

array([[0.        , 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527],
       [2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [11]:
np.sign(arr2)

array([[ 1.,  1., -1., -1.],
       [ 1., -1.,  1.,  1.],
       [-1., -1., -1.,  1.],
       [-1.,  1., -1., -1.]])

In [12]:
np.ceil(arr2)

array([[ 2.,  1., -0., -1.],
       [ 1., -0.,  1.,  1.],
       [-0., -1., -0.,  2.],
       [-0.,  2., -0., -0.]])

In [13]:
np.rint(arr2)

array([[ 1.,  1., -1., -1.],
       [ 0., -1.,  1.,  1.],
       [-0., -1., -1.,  1.],
       [-1.,  1., -1., -1.]])

In [14]:
arr2

array([[ 1.43055374,  0.6131964 , -0.52982214, -1.04819381],
       [ 0.11014858, -0.88182859,  0.60128222,  0.92179522],
       [-0.45088797, -1.18817407, -0.54545086,  1.46658887],
       [-0.53364913,  1.42595477, -0.76132483, -0.79556188]])

In [19]:
np.power(arr1,arr2)

array([[ 1.        ,  1.        ,  0.69264012,  0.31614364],
       [ 1.16497352,  0.24189577,  2.93689562,  6.01183889],
       [ 0.39156836,  0.07348417,  0.284806  , 33.67401637],
       [ 0.26551916, 38.76437986,  0.13409861,  0.11597026]])

<b> Universal Binary Functions </b>

In [24]:
np.fmax(arr1,np.sqrt(arr2))

F:\Conda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[ 1.19605758,  1.        ,  2.        ,  3.        ],
       [ 4.        ,  5.        ,  6.        ,  7.        ],
       [ 8.        ,  9.        , 10.        , 11.        ],
       [12.        , 13.        , 14.        , 15.        ]])

In [23]:
np.maximum(arr1,np.sqrt(arr2))

F:\Conda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[ 1.19605758,  1.        ,         nan,         nan],
       [ 4.        ,         nan,  6.        ,  7.        ],
       [        nan,         nan,         nan, 11.        ],
       [        nan, 13.        ,         nan,         nan]])