<h1 align="center">Indexing and Slicing techniques with ndarray Tranpose and Swap</h1>

In [1]:
import numpy as np

<b> Slicing 1D array and using copy() function</b>

In [2]:
arr=np.arange(15)
arr_slice=arr[4:8] #note the difference between a view and copy
arr_slice[:]=21
print(arr)

arr=np.arange(15)
arr_slice=arr_slice[:].copy()
arr_slice[:]=2
print(arr)


[ 0  1  2  3 21 21 21 21  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


<b> Indexing and Slicing 2D array</b>

In [3]:
arr=np.arange(15).reshape(3,5)
print(arr)
arr[0,4]#equivalnet to arr[0][4]
arr[0]=21
print(arr)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[21 21 21 21 21]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
arr=np.arange(15).reshape(3,5)
print(arr)
new=arr[1:2,1:4]
print(new)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[6 7 8]]


<b> Slicing and Indexing 3D array</b>

In [5]:
arr=np.arange(30).reshape(2,3,5)
print(arr)
new=arr[1:,1:2,1:2]
new.reshape(1,1)
print(new)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[21]]]


<b> Special Indexing #1 - Boolean Indexing </b>

In [12]:
names=np.array(["A","B","A","A","Z"])
index=np.arange(5).reshape(5,1)
print(index[names=="A"])
print(index[~(names=="A")])

[[0]
 [2]
 [3]]
[[1]
 [4]]


In [7]:
new=np.random.randn(5,5)
new

array([[ 0.35890767, -0.84398799,  0.67287007,  1.17487418,  1.05219493],
       [-0.15883914, -0.23976842, -0.27345824,  0.9463937 , -0.57594191],
       [-0.62695063, -1.17580218,  0.23833555,  0.29245843, -0.9765693 ],
       [-0.07408907,  1.96074826, -1.14527701, -1.55178269,  2.07017598],
       [ 0.46480751,  1.08218286,  1.05809004, -0.44494252, -0.98049649]])

In [8]:
new[new<0]=0
new

array([[0.35890767, 0.        , 0.67287007, 1.17487418, 1.05219493],
       [0.        , 0.        , 0.        , 0.9463937 , 0.        ],
       [0.        , 0.        , 0.23833555, 0.29245843, 0.        ],
       [0.        , 1.96074826, 0.        , 0.        , 2.07017598],
       [0.46480751, 1.08218286, 1.05809004, 0.        , 0.        ]])

<b> Special Indexing #2 - Fancy Indexing </b>

In [9]:
arr=np.arange(32).reshape(8,4)
print(arr)
arr=arr[[1,2,3,4],[0,1,2,3]]
print(arr)
#newt= arr[[1, 0, 3, 2]][:, [0, 3, 1, 2]]
#print(newt)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[ 4  9 14 19]


<b>ndarray Transpose and Swap</b>

In [ ]:
arr=np.arange(32).reshape(8,4)
x=arr.T
y=np.dot(arr,x)
print(y)

In [11]:
x=np.arange(24).reshape(2,3,4)
print(x)
print("\n")
print(x.transpose(1,0,2))
print("\n")
print(x.transpose(0,2,1))
print("\n")
print(x.swapaxes(1,2))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]


[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]


[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]
