<h1 align="center

<h1 align="center"> File I-O, Linear Algebra and Pseudorandom Number Generation with Arrays <h1>

<b> File I-O</b>

In [1]:
import numpy as np
arr=np.arange(15)
arr1=np.arange(21)
np.savez('file1.npz',a=arr,b=arr1)
zipp=np.load('file1.npz')
zipp["a"]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [2]:
np.savez_compressed('file2.npz',a=arr,b=arr1)
zipp=np.load('file1.npz')
zipp["b"]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

<b> Matrix Operations</b>

In [4]:
x=np.arange(21).reshape(3,7)
y=np.arange(21).reshape(7,3)
x@y

array([[ 273,  294,  315],
       [ 714,  784,  854],
       [1155, 1274, 1393]])

In [5]:
x.dot(y)

array([[ 273,  294,  315],
       [ 714,  784,  854],
       [1155, 1274, 1393]])

In [6]:
np.dot(x,y)

array([[ 273,  294,  315],
       [ 714,  784,  854],
       [1155, 1274, 1393]])

In [33]:
#from numpy.linalg import inv, qr, det

x=np.arange(36).reshape(6,6)
np.linalg.eig(x)


(array([ 1.10691494e+02+0.00000000e+00j, -5.69149422e+00+0.00000000e+00j,
        -2.12986244e-15+0.00000000e+00j,  4.84670913e-16+0.00000000e+00j,
        -1.37196055e-16+8.48559671e-16j, -1.37196055e-16-8.48559671e-16j]),
 array([[-0.06671357+0.j        , -0.63270151+0.j        ,
         -0.68999625+0.j        , -0.05227843+0.j        ,
         -0.15390064+0.08665854j, -0.15390064-0.08665854j],
        [-0.18278485+0.j        , -0.39467352+0.j        ,
          0.55033974+0.j        , -0.13798534+0.j        ,
         -0.05742334-0.23831675j, -0.05742334+0.23831675j],
        [-0.29885614+0.j        , -0.15664552+0.j        ,
          0.34358968+0.j        ,  0.703648  +0.j        ,
          0.6042653 +0.j        ,  0.6042653 -0.j        ],
        [-0.41492743+0.j        ,  0.08138247+0.j        ,
          0.14812253+0.j        , -0.68417275+0.j        ,
         -0.10745187+0.23498133j, -0.10745187-0.23498133j],
        [-0.53099872+0.j        ,  0.31941047+0.j        ,
     

In [32]:
np.trace(x)

105

In [37]:
np.linalg.inv(x)

array([[-1.50119988e+14, -1.06666667e+00,  1.33333333e-01,
        -2.00000000e+00,  7.50599938e+14, -6.00479950e+14],
       [-6.60527945e+15, -9.00719925e+15,  9.00719925e+15,
         1.80143985e+16,  6.00479950e+15, -1.74139186e+16],
       [ 7.95635934e+15,  1.35107989e+16, -1.35107989e+16,
        -2.25179981e+16, -8.25659932e+15,  2.28182381e+16],
       [ 3.90311968e+15, -2.25179981e+15,  7.50000000e-01,
        -4.50359963e+15, -1.50119988e+15,  4.35347964e+15],
       [-4.50359963e+15,  2.50000000e-01,  4.50359963e+15,
         4.50359963e+15, -3.33333333e-01, -4.50359963e+15],
       [-6.00479950e+14, -2.25179981e+15,  7.50000000e-01,
         4.50359963e+15,  3.00239975e+15, -4.65371961e+15]])

In [35]:
np.linalg.det(x)

-4.3755576172461056e-61

<b> Pseudo-Random Number Generation</b>

In [40]:
x=np.random.normal(size=(4,4))
x

array([[ 0.89601588, -1.23956804,  0.15973552, -0.8193865 ],
       [-0.4125801 , -0.05369795,  0.80649762, -2.35875467],
       [-0.64674802,  0.54779883, -1.6317303 , -0.09766283],
       [ 0.26238177, -0.19788576,  0.71005183,  0.37965161]])

In [50]:
x=np.random.chisquare(5,size=(4,4))
x

array([[ 0.94230022, 13.56215041,  6.44764609,  5.18076861],
       [ 3.49661805,  0.40985728,  7.44343946,  5.43012624],
       [ 6.49289593,  2.22767819,  2.17332118, 12.49672143],
       [ 3.10686284,  6.90802428,  8.02812469, 16.26164455]])

In [51]:
x=np.random.randn(2,4)
x

array([[-0.72510257,  0.16887945, -0.3917834 ,  1.49476107],
       [ 0.12655345, -0.20178787,  0.95626421,  0.81301348]])

In [52]:
x=np.random.rand(2,4)
x

array([[0.44326782, 0.37207008, 0.92354473, 0.41366317],
       [0.08320186, 0.18329646, 0.25797465, 0.23780831]])

In [53]:
x=np.random.randint(2,4)
x

2